site_name: Liger-Kernel Docs
site_url: https://linkedin.github.io/Liger-Kernel/
site_author: LinkedIn
site_description: Efficient Triton Kernels for LLM Training
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Examples: examples.md
  - Contributing: contributing.md
  - Acknowledgment: acknowledgement.md
  - License: license.md
  - API Reference:
    - Overview: api/overview.md
    - Transformers:
        - Model Patching: api/transformers/model-patch.md
        - Auto Model: api/transformers/auto-model.md
        - Liger Kernel Modules: api/transformers/modules.md
    - Chunked Loss: api/chunked_loss.md
    - Triton Ops: api/triton-ops.md
theme:
  name: material
  font:
    text: Merriweather Sans
    code: Red Hat Mono
  features:
    - navigation.footer
    - toc.follow
    - navigation.top
    - navigation.sections
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep purple

markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            show_source: false
            show_root_heading: true
            show_category_heading: true
            show_signature_annotations: true
            annotations_path: full
            show_bases: true
            show_submodules: true
            heading_level: 2
            members_order: source
            docstring_style: google
            docstring_section_style: table
            separate_signature: true
            group_by_category: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true


# Repository
repo_name: linkedin/Liger-Kernel
repo_url: https://github.com/linkedin/Liger-Kernel
edit_uri: edit/main/docs/

extra:
  social:
    - icon: simple/github
      link: https://github.com/linkedin/Liger-Kernel
